### ISSUE TITLE
with_rich_text_#{name} eager loading does not work

### ISSUE THREAD

**Issue by sedubois** [sedubois/mobility-actiontext#18]
This test currently does not pass:

https://github.com/sedubois/mobility-actiontext/blob/8ad7fbd0bd9dbc0337d585de4e8ac8bc55fb5c46/test_app/test/mobility_action_text_test.rb#L98-L106

Creating this issue for visibility, in case someone would be willing to investigate and offer a PR.

**Comment by doits** [comment]
Just found out you can do `Post.includes(:rich_text_translations)` to eager load all translations, so this could maybe be used to hook into `.with_all_rich_text`?

Not sure how to eager load one specific rich text attribute with this though.

**Comment by sedubois** [comment]
That's good to know, would you feel like submitting a PR (with test) for implementing `with_all_rich_text`?

**Comment by doits** [comment]
Sure, gave it a try in #23.

**Comment by sedubois** [comment]
Thanks @doits! `with_all_rich_text` is now fixed by #23. `with_rich_text_#{name}` still needs fixing.

**Comment by doits** [comment]
@sedubois see #24 for a possible fix.
