### ISSUE TITLE
Require only needed Rails frameworks at runtime

### ISSUE THREAD

**Issue by filippoliverani** [sedubois/mobility-actiontext#19]
The gemspec defines a runtime dependency on the wrapper `rails` gem, which brings in every Rails framework even if only a subset is needed.
https://github.com/sedubois/mobility-actiontext/blob/5697e9124ed002e57281c67e6c73519cfb2a5176/mobility-actiontext.gemspec#L30

What about requiring only `actiontext`? That [should be enough](https://github.com/rails/rails/blob/main/actiontext/actiontext.gemspec#L35-L38) to make `mobility-actiontext` work in any Rails project.

**Comment by sedubois** [comment]
Sure, don't hesitate to try out your proposed change in your project and submit a PR.
