### ISSUE TITLE
Publish gem to rubygems.org

### ISSUE THREAD

**Issue by frederfred** [sedubois/mobility-actiontext#2]
Bonjour!

Would you mind [publishing this gem to rubygems.org](https://guides.rubygems.org/publishing/#publishing-to-rubygemsorg)? It would be nice to consume it from there instead of having to do specify it like this in the `Gemfile`:

```ruby
gem "mobility-actiontext", github: "sedubois/mobility-actiontext", branch: "main"
```

Thanks!

**Comment by sedubois** [comment]
Hi Fred, you're right, I'll aim to get this done by next week. Otherwise feel free to ping again 👍

**Comment by sedubois** [comment]
@frederfred an initial release 0.1.0 has been published on RubyGems.org.

**Comment by frederfred** [comment]
Yey, thanks!

🥳
