### ISSUE TITLE
Rendering locale specific fields with Mobility.normalize_locale(locale) is not supported.

### ISSUE THREAD

**Issue by csalmeida** [sedubois/mobility-actiontext#28]
I've come across an issue where having a partial like this:

```erb
<% [:en, :ja].each do |locale| %>
  <% content = "content_#{Mobility.normalize_locale(locale)}" %>
  <%= form.label content do %>
    <%= "Content" %>
  <% end %>

  <%= form.rich_text_area content %> 
<% end %>
```

Throws this error:

```
unknown attribute 'locale' for Mobility::Backends::ActionText::RichTextTranslation.
```

This line is the cuprit but haven't been able to workout why just yet:

```erb
  <%= form.rich_text_area content %> 
```

What I'm trying to achieve is rendering locale specific fields in a single form. For example in a new article form, it would render the content field for `:en` and `:ja` locales. Is there a way to do this with rich text fields (works with other fields) and I'm missing something or could this be an issue?

Thanks for creating this Gem! 🙏

**Comment by sedubois** [comment]
[`normalize_locale`](https://github.com/shioyama/mobility/blob/2d24acbd797201137f7f05f95e4d32e32967f100/lib/mobility.rb#L183) seems to be a straightfoward method, I don't see what would be the issue with calling it. Do you have a stack trace? Could you share a repo to reproduce the issue, or add a failing test to this repo?

**Comment by csalmeida** [comment]
Thanks @sedubois, I believe this was an issue on my side. I did a prototype where everything was working but when applying it to the project I was working on I forgot to add and run the following migration:

```bash
bin/rails generate migration TranslateRichTexts
```

```ruby
class TranslateRichTexts < ActiveRecord::Migration[7.0]
  def change
    # or null: true to allow untranslated rich text
    add_column :action_text_rich_texts, :locale, :string, null: true

    remove_index :action_text_rich_texts,
                 column: [:record_type, :record_id, :name],
                 name: :index_action_text_rich_texts_uniqueness,
                 unique: true
    add_index :action_text_rich_texts,
              [:record_type, :record_id, :name, :locale],
              name: :index_action_text_rich_texts_uniqueness,
              unique: true
  end
end
```

Hope this didn't took too much of your time!
