### ISSUE TITLE
Syntax for accessing records via query

### ISSUE THREAD

**Issue by dvodvo** [sedubois/mobility-actiontext#34]
giving the indices
```
add_index :action_text_rich_texts,              [:record_type, :record_id, :name, :locale]
```
and assuming a context of exporting a set of translated record_ids, what is the proper syntax for querying/accessing the table for such an array?  *struggled a bit with this for basic mobility*

I believ it evolves from:
Mobility::Activerecord::StringTranslation
Mobility::Activerecord::TextTranslation
to
Mobility::Backends::ActionText::PlainTextTranslation
Mobility::Backends::ActionText::RichTextTranslation
?

Assuming klass.translatable_content column, how does one call a method, say
```
truncate(klass.translatable_content column, length: 200)
```
?

**Comment by sedubois** [comment]
Hi @dvodvo, thanks for writing in. Once you've [set up](https://github.com/sedubois/mobility-actiontext#installation) Mobility and Action Text, your translated Action Text should be accessible using the standard Mobility APIs, e.g. `record.content`. A DB index is suggested to ensure fast access to the records and (optionally) to enforce uniqueness, but it doesn't impact the way to read/write attributes using the Mobility API.

If you have further questions, please feel free to reopen with code which allows to reproduce your issue.
