### ISSUE TITLE
Ruby minimum versions

### ISSUE THREAD

**Issue by thatdoogieguy** [sedubois/mobility-actiontext#4]
Looking at this gem it seems like it may fill a very obvious gap in the mobility core gem, but I'm wondering if the Ruby minimum version can be loosened to support all current Rails supported Ruby versions? For example, we have a number of applications using v2.6 for various reasons and we are unable to use this gem without forking or other techniques due to a fairly restrictive Ruby version. 

Is this something technically limiting to Ruby 2.7 or just a design choice, or something that can ideally be changed to support a wider audience.

**Comment by sedubois** [comment]
The version just corresponds to what I needed when developing this gem. Don’t hesitate to submit a PR with a wider test matrix!
